title: Tyson Benard
url: "https://mandalorian444.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
skills: "VFX Artist - 3D Modeler - C++ Developer"

collections:
  projects:
    output: true
  posts:
    output: true

# Footer settings
footer:
  copyright: Tyson Benard

colors:
  primary-rgb: "24,128,188"
  primary-grey-rgb: "51,51,51"
  background: "33,33,33"
  background-darker: "25,25,25"
  horizontal-rule: "255,255,255"
  navbar-background: "51,51,51"
  navbar-text: "255,255,255"
  navbar-text-hover: "150,150,150"
  projects-background: "33,33,33"
  proficiencies-text: "82,151,255"
  about-background: "24,128,188"
  section-border: "100,100,100"
